### ISSUE TITLE
Deployment fails during SCCM Installation due to missing SQL ODBC driver

### ISSUE THREAD

**Issue by sn8kesec** [Synzack/ludus_sccm#1]
## Issue

The SCCM installation on the site server fails during deployment because the host does not have the ODBC SQL driver installed. 

## Error Message

`TASK [synzack.ludus_sccm.ludus_sccm_siteserver : Fail ansible on failed install] ***
[WARNING]: Could not match supplied host pattern, ignoring: ADMIN-nexus-3-oss
fatal: [XX-sccm-sitesrv]: FAILED! => {"changed": false, "msg": "SCCM failed to install. Check the log output above for details."}`

**Log from SCCM Installer:**

`ERROR: Failed to connect to SQL Server sccm-sql.ludus.lab to determine if it is a cluster, or failed to run the query.  $$<Configuration Manager Setup><06-06-2024 23:10:03.979+240><thread=1336 (0x538)> `

## Cause
Configuration Manager version 2309 and higher requires the ODBC SQL driver to be installed. https://learn.microsoft.com/en-us/mem/configmgr/core/plan-design/changes/whats-new-in-version-2309#introducing-sql-odbc-driver-support-for-configuration-manager

## Fix
I was able to get the installation to work after manually installing the ODBC driver on the site server and redeploying the range

**Comment by Synzack** [comment]
Looks like the Microsoft current SCCM branch has been updated to 2403. The lab was initially configured for 2303. I am currently working to update it. Thanks for mentioning the ODBC driver for an interim fix!

**Comment by Synzack** [comment]
Updated the script to use a static download URL for SCCM 2303. This should solve the issue as ODBC is not a pre-req in this version. I will probably create a new branch for the 2403 version. 

If you downloaded v1.0.0 - Be sure to remove "MCM_Configmgr_2303.exe" from the following directory on your Ludus host:
_/opt/ludus/resources/sccm_

Then destroy and redeploy.
