### ISSUE TITLE
Deployment requires non-default Ludus template for Windows 10

### ISSUE THREAD

**Issue by sn8kesec** [Synzack/ludus_sccm#2]
## Issue
The deployment fails if the non-default Ludus template "win10-21h2-x64-enterprise-template" is built.

## Error Message
`TASK [synzack.ludus_sccm.ludus_sccm_siteserver : Copy ISO file to Site Server]
fatal: [XX-sccm-sitesrv]: FAILED! => {"changed": false, "dest": "C:\\ludus\\sccm\\win10.iso", "msg": "Could not find or access '/var/lib/vz/template/iso/19044.1288.211006-0501.21h2_release_svc_refresh_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option", "src": "/var/lib/vz/template/iso/19044.1288.211006-0501.21h2_release_svc_refresh_CLIENTENTERPRISEEVAL_OEMRET_x64FRE_en-us.iso"}`

## Fix
I was able to get the deployment to work after building the Windows 10 template on Ludus.
`ludus templates build -n win10-21h2-x64-enterprise-template`

**Comment by Synzack** [comment]
Thanks for pointing this out! I will update PXE to use the default Windows 11 template. Thank you for posting the temporary fix.

**Comment by Synzack** [comment]
Updated the collection to use the default Ludus Win11 template.
